# Render Blueprint - Web Service Laravel (Pedra Rica)

services:
  - type: web
    name: pedra-rica
    runtime: docker
    repo: https://github.com/Renatomalebo10/Pedra-Rica
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    numInstances: 1
    autoDeployTrigger: 'commit'
    healthCheckPath: /up
    preDeployCommand: >
      sh -c "
      php artisan migrate --force &&
      { if [ -z \"$APP_KEY\" ] || [ \"$APP_KEY\" = \"base64:\" ]; then php artisan key:generate; fi; } &&
      { VALUE=\$(php artisan tinker --execute 'echo \\App\\Models\\User::where(\"email\",\"admin@pedrarica.com\")->exists() ? \"1\":\"0\";'); if [ \"\$VALUE\" != \"1\" ]; then php artisan db:seed --force; fi; } &&
      php artisan optimize:clear &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "27216"
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stack
      - key: FILESYSTEM_DISK
        value: local
