# Render Blueprint - Web Service Laravel (Pedra Rica)

services:
  - type: web
    name: pedra-rica
    runtime: docker
    repo: https://github.com/Renatomalebo10/Pedra-Rica
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    plan: free
    numInstances: 1
    autoDeployTrigger: 'commit'
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stack
      - key: FILESYSTEM_DISK
        value: s3
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: auto
      - key: AWS_BUCKET
        sync: false
      - key: AWS_URL
        sync: false
      - key: AWS_ENDPOINT
        sync: false
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: "false"
